# Generated by Django 2.2.13 on 2020-07-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('phone', models.CharField(default='-', max_length=25)),
                ('approved', models.IntegerField(default=0)),
                ('room', models.IntegerField(default=0)),
                ('qm', models.IntegerField(default=0)),
                ('location', models.CharField(default='-', max_length=500)),
            ],
        ),
    ]
